# Generated by Django 4.1.2 on 2022-11-06 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='DD-MM-AAAA')),
                ('timeblock', models.IntegerField(blank=True, choices=[(1, '09:00 - 10:00'), (2, '10:00 - 11:00'), (3, '11:00 - 12:00'), (4, '12:00 - 13:00'), (5, '13:00 - 14:00'), (6, '14:00 - 15:00'), (7, '15:00 - 16:00'), (8, '16:00 - 17:00'), (9, '17:00 - 18:00')], default='Elija el horario', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'timeblock')},
            },
        ),
    ]
