# Generated by Django 4.1.2 on 2022-11-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
